import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { AmbiguousInferenceFailure, DeterministicTaskFailure, IMAGE_SESSION_LIMITS, planImageSession, readImageSessionReceipt, runImageSession, writeImageSessionReceipt, type ImageSessionDeps, type ImageSessionReceipt } from "./image-session";

const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const task = (n: number, patch: Record<string, unknown> = {}) => ({ id: id(n), status: "waiting_for_gpu", mode: "text_generation", referenceImage: null, prompt: `private-fixture-${n}`, width: 768, height: 768, steps: 30, cfg: 4, loraStrength: .8, seed: n, sampler: "Euler", createdAt: `2026-07-26T00:${String(n).padStart(2, "0")}:00Z`, ...patch }) as any;

function fake(input: { deterministic?: string; infrastructure?: boolean; acceptedResume?: boolean; existingOrder?: boolean; late?: boolean } = {}) {
  const events: string[] = []; let stored: ImageSessionReceipt | null = input.acceptedResume || input.existingOrder ? { schemaVersion: 1, sessionId: "resume", orderId: "order", selectedTaskIds: [id(1)], currentTaskId: input.acceptedResume ? id(1) : null, modelStage: "succeeded", tasks: { [id(1)]: { terminal: "not_started", inferenceState: input.acceptedResume ? "accepted" : "not_started" } }, completedTaskCount: 0, failedTaskCount: 0, timestamps: {}, idleDeadlineAt: "2026-07-26T00:15:00Z", hardDeadlineAt: "2026-07-26T04:00:00Z", cancellationState: "not_started", firstInfrastructureError: null } : null;
  let nowMs = input.late ? Date.parse("2026-07-26T00:14:59Z") : Date.parse("2026-07-26T00:00:00Z"); const pool = [task(1), task(2), task(3)];
  const deps: ImageSessionDeps = { now: () => new Date(nowMs).toISOString(), nowMs: () => nowMs, persist: (value) => { stored = structuredClone(value); }, load: () => stored, reconcileZeroActiveOrders: async () => { events.push("reconcile"); }, preflight: async () => { events.push("preflight"); }, createOrder: async () => { events.push("create"); return { orderId: "one-order" }; }, armWatchdog: async () => { events.push("arm"); }, prepareRuntimeOnce: async () => { events.push("runtime"); }, verifyModelsOnce: async () => { events.push("models"); }, readEligible: async (taskId) => pool.find((item) => item.id === taskId), claim: async (value) => { events.push(`claim:${value.id}`); return { token: `token-${value.id}` }; }, startHeartbeat: (taskId) => ({ stop: () => events.push(`stop:${taskId}`), assertHealthy: () => {} }), writeTaskReceipt: async (taskId, state) => { events.push(`receipt:${taskId}:${state}`); }, submitInference: async (value) => { events.push(`post:${value.id}`); if (input.infrastructure && value.id === id(2)) throw new Error("agent_transport_outage_exceeded"); }, pollAndFinalize: async (value) => { events.push(`finalize:${value.id}`); if (input.deterministic === value.id) throw new DeterministicTaskFailure("result_dimensions_mismatch"); }, failTask: async (taskId) => { events.push(`fail:${taskId}`); }, cancelExactOrder: async (orderId) => { events.push(`cancel:${orderId}`); }, confirmNoActiveOrders: async () => { events.push("zero"); }, disarmWatchdog: async () => { events.push("disarm"); } };
  return { deps, events, plan: planImageSession(pool), get stored() { return stored; } };
}

async function main() {
  const ranked = planImageSession([task(3), task(2, { priority: "urgent" }), task(1), task(4, { status: "completed" }), task(5, { localClaim: { x: true } }), task(6, { referenceImage: "x" }), task(7, { steps: 2 })]);
  assert.deepEqual(ranked.selectedTaskIds, [id(2), id(1), id(3)]); assert.equal(ranked.eligibleCount, 3); assert.equal(planImageSession(Array.from({ length: 12 }, (_, n) => task(n + 1))).count, IMAGE_SESSION_LIMITS.maxBatchSize);
  const happy = fake(); const done = await runImageSession({ sessionId: "session", plan: happy.plan, normalGenerationMs: 1, cleanupMs: 1 }, happy.deps);
  assert.equal(happy.events.filter((event) => event === "create").length, 1); assert.equal(happy.events.filter((event) => event === "models").length, 1); assert.deepEqual(happy.events.filter((event) => event.startsWith("claim:")), [`claim:${id(1)}`, `claim:${id(2)}`, `claim:${id(3)}`]); assert.equal(happy.events.filter((event) => event.startsWith("post:")).length, 3); assert.equal(done.completedTaskCount, 3); assert.equal(happy.events.filter((event) => event === "zero").length, 2);
  const deterministic = fake({ deterministic: id(1) }); const afterFailure = await runImageSession({ sessionId: "session", plan: deterministic.plan, normalGenerationMs: 1, cleanupMs: 1 }, deterministic.deps); assert.equal(afterFailure.failedTaskCount, 1); assert.ok(deterministic.events.includes(`post:${id(2)}`));
  const infra = fake({ infrastructure: true }); await assert.rejects(() => runImageSession({ sessionId: "session", plan: infra.plan, normalGenerationMs: 1, cleanupMs: 1 }, infra.deps), /agent_transport_outage_exceeded/); assert.equal(infra.events.includes(`post:${id(3)}`), false);
  const ambiguous = fake({ acceptedResume: true }); await assert.rejects(() => runImageSession({ sessionId: "resume", plan: ambiguous.plan }, ambiguous.deps), AmbiguousInferenceFailure); assert.equal(ambiguous.events.length, 0);
  const existingOrder = fake({ existingOrder: true }); await assert.rejects(() => runImageSession({ sessionId: "resume", plan: existingOrder.plan }, existingOrder.deps), /image_session_resume_existing_order_requires_manual_reconciliation/); assert.equal(existingOrder.events.includes("create"), false); assert.ok(existingOrder.events.includes("cancel:order"));
  const late = fake({ late: true }); const drained = await runImageSession({ sessionId: "late", plan: late.plan, normalGenerationMs: 15 * 60_000, cleanupMs: 60_000 }, late.deps); assert.equal(drained.completedTaskCount, 0); assert.equal(late.events.some((event) => event.startsWith("post:")), false); assert.ok(late.events.includes("cancel:one-order"));
  const root = mkdtempSync(path.join(os.tmpdir(), "image-session-receipt-")); try { const receiptPath = path.join(root, "receipt.json"); writeImageSessionReceipt(receiptPath, done); assert.deepEqual(readImageSessionReceipt(receiptPath), done); } finally { rmSync(root, { recursive: true, force: true }); }
  assert.equal(JSON.stringify(done).includes("private-fixture"), false); assert.equal(happy.events.some((event) => /provider|clore/i.test(event)), false);
  console.log(JSON.stringify({ ok: true, planner_ordering_and_exclusions: true, zero_mutation_planning: true, one_model_stage_many_tasks: true, one_at_a_time_claim_and_single_post: true, deterministic_failure_continues: true, infrastructure_and_ambiguous_fail_closed: true, atomic_receipt_and_idle_cleanup: true, secrets_and_prompts_absent: true }));
}
void main();
