import assert from "node:assert/strict";
import { mkdtempSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { completeStage3OCheckpoint, initialStage3OState, nextStage3OCheckpoint, readStage3OState, STAGE3O_CHECKPOINTS } from "./stage3o-live-state";
import { rankStage3OCandidates, runStage3THardwareAudit, stage3SHardwareInspectionCommand, stage3SVideoFailureMetadata, validateStage3THardwareEvidence } from "./generation-live-session";
import type { GpuCandidate } from "./gpu-providers/types";
import type { GpuTarget } from "./gpu-providers/types";
import type { sshCommand } from "./gpu-providers/common";
import { buildStage3OWanWorkflow, validateStage3OWanWorkflow } from "./stage3o-wan-executor";
import { readFileSync } from "node:fs";

const file = path.join(mkdtempSync(path.join(os.tmpdir(), "stage3o-live-")), "state.json"); let state = initialStage3OState();
for (const checkpoint of STAGE3O_CHECKPOINTS) state = completeStage3OCheckpoint(state, checkpoint, { tested: true }, file);
assert.equal(nextStage3OCheckpoint(readStage3OState(file)), null); assert.deepEqual(state.completed, [...STAGE3O_CHECKPOINTS]);
assert.ok(state.completed.indexOf("image_generated") < state.completed.indexOf("image_synced")); assert.ok(state.completed.indexOf("image_synced") < state.completed.indexOf("flux_unloaded")); assert.ok(state.completed.indexOf("flux_unloaded") < state.completed.indexOf("wan_restored")); assert.ok(state.completed.indexOf("outputs_synced") < state.completed.indexOf("runtime_stopped")); assert.ok(state.completed.indexOf("runtime_stopped") < state.completed.indexOf("order_cancelled"));
const candidate = (id: string, disk: number, price: number): GpuCandidate => ({ id, gpuType: "RTX 4090", priority: 1, vramGb: 24, gpuCount: 1, minimumRamGb: 64, containerDiskGb: disk, volumeGb: 0, hourlyUsd: price, availability: "High", interruptible: false });
assert.deepEqual(rankStage3OCandidates([candidate("2", 200, 0.4), candidate("1", 200, 0.5), candidate("bad", 120, 0.1)], ["1"]).map((item) => item.id), ["1", "2"]);
assert.deepEqual(rankStage3OCandidates([candidate("28726", 200, 0.4), candidate("3", 200, 0.5)], []).map((item) => item.id), ["3"], "manual golden server must not be reused");
assert.deepEqual(rankStage3OCandidates([candidate("small-disk", 179, 0.2), { ...candidate("low-vram", 200, 0.2), vramGb: 22 }, { ...candidate("a40", 200, 0.2), gpuType: "A40" }], []).map((item) => item.id), []);
assert.deepEqual(rankStage3OCandidates([candidate("ordinary", 200, 0.1), candidate("29167", 200, 0.2), candidate("105178", 200, 0.3)], []).map((item) => item.id), ["29167", "105178", "ordinary"], "deployment/SSH-verified hosts must be preferred and not generically excluded");
assert.deepEqual(rankStage3OCandidates([{ ...candidate("105178", 200, 0.1), reliability: 1 }, { ...candidate("29167", 200, 0.3), reliability: 0.9 }], []).map((item) => item.id), ["29167", "105178"], "Stage 3U must explicitly prefer server 29167 before server 105178");
const hardwareCommand = stage3SHardwareInspectionCommand(); assert.ok(hardwareCommand.indexOf("mkdir -p /workspace") < hardwareCommand.indexOf("df -B1 /workspace")); assert.ok(hardwareCommand.includes("cuda_device=")); assert.ok(hardwareCommand.includes("root_disk_bytes")); assert.ok(hardwareCommand.includes("docker_available=false")); assert.ok(hardwareCommand.includes("network_probe")); assert.ok(hardwareCommand.includes("torch_present=")); assert.ok(hardwareCommand.includes("find_spec")); assert.ok(!hardwareCommand.includes("python3 -c 'import torch;"), "a pristine host must not fail inspection before bootstrap installs torch");
const fakeTarget = {} as GpuTarget;
const audit = runStage3THardwareAudit(fakeTarget, ((_target: GpuTarget, command: string) => ({ status: 0, stdout: command.includes("query-gpu") ? "NVIDIA GeForce RTX 4090, 24564 MiB, 0 MiB, 570.00\n" : command === "free -b" ? "Mem: 68719476736 1 1 1 1 1\n" : command === "df -B1 /workspace" ? "Filesystem 1B-blocks Used Available Use% Mounted on\n/dev/root 858993459200 1 858993459199 1% /workspace\n" : command.includes("find_spec") ? "torch_installed=false\n" : command.includes("docker_available") ? "docker_available=false\n" : "ok\n", stderr: "" })) as typeof sshCommand);
assert.equal(audit.find((item) => item.label === "torch_optional")?.stdout.trim(), "torch_installed=false"); assert.equal(validateStage3THardwareEvidence(audit).torchInstalled, false);
assert.deepEqual(stage3SVideoFailureMetadata(new Error("video failed")), { errorClass: "video failed", imagePreserved: true });
assert.equal(validateStage3OWanWorkflow(buildStage3OWanWorkflow()).durationSeconds, 2.0625);
const liveSource = readFileSync("scripts/generation-live-session.ts", "utf8"); assert.ok(liveSource.includes("clore:watchdog:local:install")); assert.ok(liveSource.includes("clore:watchdog:remote:arm")); assert.ok(liveSource.includes("clore:watchdog:remote:disarm")); assert.ok(liveSource.includes("/Disable")); assert.ok(liveSource.includes('cloreProfile: "clore_key_only"')); assert.ok(liveSource.includes("MAX_HOST_ATTEMPTS = 2")); assert.ok(liveSource.includes("MAX_FAILED_DEPLOYMENT_SPEND_USD = 0.4")); assert.ok(liveSource.includes("readCloreSshAuthEvidence()"), "checkpoint must use observed SSH authentication evidence");
const firstImageSource = readFileSync("scripts/gpu-first-image.ts", "utf8"); assert.ok(firstImageSource.includes("sed -i 's/\\\\r$//' /workspace/clore-light-bootstrap.sh"), "Windows-to-Linux bootstrap transfer must normalize CRLF before execution");
assert.ok(firstImageSource.includes("/system_stats") && firstImageSource.includes("?clientId=") && firstImageSource.includes("attempt <= 3"), "SSH tunnel verification must wait for HTTP and retry a client-identified WebSocket");
const bootstrapSource = readFileSync("scripts/clore/clore-light-bootstrap.sh", "utf8"); assert.ok(bootstrapSource.includes("build-essential gcc g++ make libc6-dev linux-libc-dev"), "host-mode bootstrap must include the compiler and C/Python headers required by Triton");
console.log("Stage 3O checkpoint resume, sequential image-unload-video flow, candidate policy, and cleanup order passed.");
