import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fluxCacheCurrentKey, fluxCacheFiles, fluxCacheManifestKey, buildFluxCacheManifest } from "./flux4090-cache";

assert.equal(fluxCacheFiles.length, 3);
assert.equal(fluxCacheCurrentKey, "production/rtx4090/image/current.json");
assert.match(fluxCacheManifestKey, /^production\/rtx4090\/image\/revisions\//);
const manifest = buildFluxCacheManifest();
assert.equal(manifest.files.length, 3);
for (const file of manifest.files) {
  assert.match(file.sha256, /^[a-f0-9]{64}$/);
  assert.ok(file.size_bytes > 1024 * 1024);
  assert.match(file.key, /^production\/rtx4090\/image\/revisions\//);
}
const source = readFileSync(path.join(process.cwd(), "scripts", "model-cache", "flux4090-cache.ts"), "utf8");
assert.match(source, /PART_BYTES = 64 \* 1024 \* 1024/);
assert.match(source, /CONCURRENT_PARTS = 2/);
assert.match(source, /HTTP_TIMEOUT_MS = 120_000/);
assert.match(source, /FLUX_R2_SEED_STATE_DIR/);
assert.match(source, /seed_time_limit_reached/);
assert.match(source, /CompleteMultipartUploadCommand/);
assert.match(source, /ListPartsCommand/);
assert.match(source, /UploadPartCommand/);
assert.match(source, /CreateMultipartUploadCommand/);
assert.match(source, /sort\(\(a, b\) => a\.number - b\.number\)/);
assert.match(source, /duplicate multipart part/);
assert.match(source, /missing multipart part/);
assert.match(source, /missing ETag/);
assert.match(source, /sanitizeS3Error/);
assert.match(source, /R2 final object missing before manifest publish/);
assert.match(source, /\.secrets/);
assert.match(source, /verifyFlux4090Cache/);
assert.match(source, /gpu_readonly_restore_probe/);
assert.match(source, /Range: `bytes=/);
const workflow = readFileSync(path.join(process.cwd(), ".github", "workflows", "flux4090-model-cache.yml"), "utf8");
assert.match(workflow, /timeout-minutes: 180/);
assert.match(workflow, /group: flux4090-model-cache/);
assert.match(workflow, /permissions:\s*\n\s*contents: read/);
assert.match(workflow, /npm run model-cache:seed:flux4090/);
assert.match(workflow, /npm run model-cache:status:flux4090/);
assert.match(workflow, /npm run model-cache:verify:flux4090/);
assert.match(workflow, /npm run model-cache:probe:flux4090/);
assert.match(workflow, /FLUX_R2_RECOVERY_STAGING_KEYS_JSON/);
assert.match(workflow, /retention-days: 7/);
assert.doesNotMatch(workflow, /build-push-action|packages:\s*write/);
console.log("FLUX R2 multipart, resume, hosted runner workflow, and publish-last tests passed.");
